### ISSUE TITLE
Updating version ?

### ISSUE THREAD

**Issue by Altalus** [PepeCitron/vintagestory-server#1]
Hi !

I am attempting to force version 1.19.8 as at the moment the container seems to only have 1.18

I added SERVER_VERSION="1.19.8" but it did not change anything. Any idea ?

**Comment by PepeCitron** [comment]
I fixed the forced update version and updated the Dockerfile to 1.19.8 a9eac1fa2e2922038c788b4e8f81f440a1a994ba 0cd49534c4b9e5d86ad4192b71a0589141d64bef
